version: '3.7'

services:
  frontend:
     container_name: frontend
     build:
       context: .
       dockerfile: Dockerfile.react
     volumes:
       - '/Users/duttk/apps/apps:/frontend'
       - '/frontend/node_modules'
       - '/Users/duttk/apps/apps/package.json:/frontend/package.json'
     ports:
       - 3000:3000
     environment:
       - CHOKIDAR_USEPOLLING=true
     stdin_open: true
     tty: true
  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - '/Users/duttk/apps/apps/api:/backend'
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=numeral.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    stdin_open: true
    tty: true

