version: '3.7'

services:
  frontend:
    image: frontend:tag
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
        - './apps:/frontend'
        - '/frontend/node_modules'
        - './apps/package.json:/frontend/package.json'
    ports:
        - 3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  backend:
    image: backend:tag
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
       - './apps/api:/backend'
    ports:
       - 5000:5000
    environment:
       - FLASK_APP=numeral.py
       - LC_ALL=C.UTF-8
       - LANG=C.UTF-8
    stdin_open: true
    tty: true
