version: '3.7'

services:
  frontend:
    image: gcr.io/engaged-style-276720/react:v1
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
        - './apps:/frontend'
        - '/frontend/node_modules'
        - './apps/package.json:/frontend/package.json'
    ports:
        - 3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  backend:
    image: gcr.io/engaged-style-276720/flask:v1
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
       - './apps/api:/backend'
       - './apps/build:/backend/build'
    ports:
       - 8080:8080
    environment:
       - FLASK_APP=numeral.py
       - LC_ALL=C.UTF-8
       - LANG=C.UTF-8
    stdin_open: true
    tty: true
