# pull official base image
FROM ubuntu:18.04
# set working directory
WORKDIR /backend

EXPOSE 5000

COPY apps/requirements.txt ./requirements.txt

RUN apt-get update -y && apt-get install -y python3.7 python3-pip
RUN pip3 install --no-cache-dir -r requirements.txt

ENV FLASK_APP=api/numeral.py
# add app
COPY ./apps/api/ ./

# start app
CMD ["flask", "run", "--host", "0.0.0.0"]

